/*
  # Ajout de mots-clés courants en cybersécurité
  
  1. Données insérées
    - Ajout de mots-clés fréquemment utilisés en cybersécurité
    - Termes en français et en anglais
    - Couvre différents thèmes : mots de passe, phishing, réseaux, confidentialité, etc.
  
  2. Notes importantes
    - Utilise ON CONFLICT DO NOTHING pour éviter les doublons
    - Les mots-clés sont en minuscules pour cohérence
*/

INSERT INTO keywords (keyword) VALUES
  ('mot de passe'),
  ('password'),
  ('sécurité'),
  ('security'),
  ('authentification'),
  ('authentication'),
  ('hameçonnage'),
  ('email'),
  ('arnaque'),
  ('scam'),
  ('lien'),
  ('link'),
  ('malware'),
  ('virus'),
  ('antivirus'),
  ('pare-feu'),
  ('firewall'),
  ('vpn'),
  ('wifi'),
  ('réseau'),
  ('network'),
  ('chiffrement'),
  ('encryption'),
  ('données'),
  ('data'),
  ('confidentialité'),
  ('privacy'),
  ('backup'),
  ('sauvegarde'),
  ('mise à jour'),
  ('update'),
  ('téléchargement'),
  ('download'),
  ('navigation'),
  ('browser'),
  ('cookies'),
  ('tracking'),
  ('social'),
  ('réseaux sociaux'),
  ('messagerie'),
  ('chat'),
  ('smartphone'),
  ('mobile'),
  ('application'),
  ('app'),
  ('cloud'),
  ('stockage'),
  ('partage'),
  ('share'),
  ('permission'),
  ('droits'),
  ('access'),
  ('accès'),
  ('identité'),
  ('identity'),
  ('usurpation'),
  ('vol'),
  ('theft'),
  ('protection'),
  ('sécuriser'),
  ('secure'),
  ('risque'),
  ('risk'),
  ('menace'),
  ('threat'),
  ('attaque'),
  ('attack'),
  ('hack'),
  ('pirate'),
  ('hacker'),
  ('ransomware'),
  ('rançongiciel'),
  ('spyware'),
  ('espion'),
  ('trojan'),
  ('cheval de troie'),
  ('exploit'),
  ('faille'),
  ('vulnerability'),
  ('vulnérabilité'),
  ('patch'),
  ('correction'),
  ('gestionnaire'),
  ('manager'),
  ('clé'),
  ('key'),
  ('token'),
  ('jeton'),
  ('session'),
  ('connexion'),
  ('login'),
  ('déconnexion'),
  ('logout'),
  ('compte'),
  ('account'),
  ('profil'),
  ('profile'),
  ('paramètres'),
  ('settings'),
  ('configuration'),
  ('config'),
  ('alerte'),
  ('alert'),
  ('notification'),
  ('surveillance'),
  ('monitoring'),
  ('audit'),
  ('log'),
  ('journal'),
  ('historique'),
  ('history'),
  ('navigateur'),
  ('extension'),
  ('plugin'),
  ('https'),
  ('ssl'),
  ('tls'),
  ('certificat'),
  ('certificate')
ON CONFLICT (keyword) DO NOTHING;